### ISSUE TITLE
Import does not recognise exported file

### ISSUE THREAD

**Issue by plinkykev** [EdwynZN/amiibo_network#6]
Steps:
1. Exported file off one Android device (Moto G6+ on Android 9) 
2. Sent via Bluetooth to new phone (OnePlus 7T on Android 10)
3. Selected import
4. Browsed to file using file manager inside app
5. Selected received file
6. Error shown: "This isn't an Amiibo list"

![Screenshot_20200806-191055](https://user-images.githubusercontent.com/57759672/89555379-a65aba80-d818-11ea-9683-e1a627baca96.jpg)

![Screenshot_20200806-190221](https://user-images.githubusercontent.com/57759672/89554422-81197c80-d817-11ea-92e5-8bd0dfca2ec7.jpg)

**Comment by EdwynZN** [comment]
That's really weird to see, I wasn't aware that you could send a json file for bluetooth (it always failed to export that format type using bluetooth), does the file exported from device to device successfully? Did you try other methods to share it to your other device?

- Gmail 
- Google Drive
- Messagin App (Whatsapp, Telegram, etc)

Or if you could attach the file from your receiver device (Oneplus 7T) to check if the file transferred correctly

**Comment by plinkykev** [comment]
Thanks for the reply. For Bluetooth, I did that using the "share" option from notification area, then selected Bluetooth to transmit the file. It arrives in the "(Internal shared storage)\bluetooth" folder on the new device, and I used the file browser option within the app to find it.

Today I exported again, and transferred the file via a PC. I copied the file from old device "(Internal shared storage)\Android\data\com.dartz.amiibo_network\files\Documents" and put it in the same folder on the new device. I imported in the app using same method of File Manager to find the file and then select it. This time the file imported OK.

So, I have my data, which is good, but there is some weird problem about sending from one device to another using Bluetooth.
I cannot attach the files to this ticket, but I uploaded them here ( https://gofile.io/d/Wqz96c ) in a zip file, if you want to analyse them.

**Comment by EdwynZN** [comment]
I tested your files without problem in Android 9 and Android 7, but what i saw was that if you go to your file explorer app, long press the file and then share the bluetooth option is not showed (Gmail, Drive, messaging apps shows fine), so maybe this file type is not supported for sharing with bluetooth on Android (?), the best thing to do right now is comply to the Android documentation and use the same share system as the file explorer app. 

![Screenshot_20200807-174602](https://user-images.githubusercontent.com/16828084/89694062-12e7bf00-d8d6-11ea-8a5f-13433bb12ba8.png)

What I found weird is that months ago when I was testing this functionality of sharing bluetooth never actually worked (it always said 'transfer failed' and I thought it was because the format file)
