### ISSUE TITLE
Backup restore function doesn't work 

### ISSUE THREAD

**Issue by Ralf776** [EdwynZN/amiibo_network#70]
Hello,

I like the app, it's great, now I have changed my phone and used the backup from the documents folder.
Sadly it's not restore able.
My older backups from November 2023 are working. 
Files since December 2023 doesn't work.
I tried a new backup on my new phone and it's also not restore able.

Would be awesome, if a fix would be possible.

**Comment by EdwynZN** [comment]
Hello, can you upload/share your december file, I see now there is a malformed amiibo that doesn't let read the file, I'll need to update that

**Comment by Ralf776** [comment]
[MyAmiiboNetwork_20240406_160706.json](https://github.com/EdwynZN/amiibo_network/files/14905063/MyAmiiboNetwork_20240406_160706.json)

Thank you very much. I have uploaded my newest state.
If you need the older one, please inform me.

**Comment by EdwynZN** [comment]
[MyAmiiboNetwork_20240406_160706.json](https://github.com/EdwynZN/amiibo_network/files/14907179/MyAmiiboNetwork_20240406_160706.json)

Yeah it seems some update I pushed in december started making malformed exported files so they're unreadable, I can fix it for a future update but I don't know if I can fix the previous files, I had to manually change the wrong letter so it could be read.

The problem is because a yu gi oh card with the name Tatsuhisa “Luke” Kamijō (the last letter and " gets replaced for an unreadable letter, I don't know why it suddenly happened after december)

**Comment by EdwynZN** [comment]
can you share also your previous file just to compare it and be sure

**Comment by Ralf776** [comment]
[MyAmiiboNetwork_20231203_204306.json](https://github.com/EdwynZN/amiibo_network/files/14907989/MyAmiiboNetwork_20231203_204306.json)

Thank you very much for fixing my file, this should be the first of my not working files.

[MyAmiiboNetwork_2023-11-26.json](https://github.com/EdwynZN/amiibo_network/files/14908016/MyAmiiboNetwork_2023-11-26.json)

This should be my last working file.

**Comment by EdwynZN** [comment]
Yeah it seems the problem is that yugioh card with weird characters which results in:

`Tatsuhisa Luke KamijM`

but should be: 

`Tatsuhisa “Luke” Kamijō`

And when reading it back gives an error, I have a fix to avoid that but I'll check in the week if I can make the previous versions be readable

**Comment by Ralf776** [comment]
Thank you very much for your support.

**Comment by EdwynZN** [comment]
#71 Fixing import and export of json file
